test "component equality":
	assert (formatted "<rainbow>Hello!") is (formatted "<rainbow>Hello!") with "components with virtual components failed comparison"

test "component serialization":
	# verify no warning
	parse:
		set {x} to line 1 of lore of {_item}
	assert last parse logs are not set

test "component contains":
	set {_item} to a dirt block with lore "<red>Hello world!"
	assert last element of lore of {_item} contains "<red>Hello"
