name: Java 17 CI (MC 1.19.4-1.20.4)

on:
    push:
        branches:
            - master
            - 'dev/**'
    pull_request:

jobs:
    build:
        if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  submodules: recursive
            - name: validate gradle wrapper
              uses: gradle/actions/wrapper-validation@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v5
              with:
                  java-version: '21'
                  distribution: 'adopt'
                  cache: gradle
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build Skript and run test scripts
              run: ./gradlew clean skriptTestJava17
            - name: Upload Nightly Build
              uses: actions/upload-artifact@v4
              if: success()
              with:
                  name: skript-nightly
                  path: build/libs/*
